#!/usr/bin/env node

var path = require('path'),
    _ = require('underscore');

var basePath = process.argv[1].split(path.sep),
    self = basePath.pop(),
    input = '',
    stats = { docs: 0, updates: 0 },
    index = {},
    updates = {},
    options = {},
    tmp;

var usageInfo = `
Usage: cat data.json | ./node_modules/.bin/${self} [-ah] index.json > data-edited.json

Description:

  Take a list of JSON objects with an \`_id\` property on standard input and
  apply changes to it.  The changes are based on an index file that is a list
  of JSON objects with an \`id\` property and the other properties you want to
  change.

  This command is basically a wrapper around the Underscore.js \`extend\`
  function and calls it like this:

      newDoc = _.extend(origDoc, change);

Options:
  
  -h  This help information.

  -a  Update all occurrences of an object, rather than just updating the first
      or top level occurrence.  Be careful when using this on embedded
      documents, because this can cause conflicts if the embedded document is
      modified but the referenced doc is not updated.  To modify embedded
      documents properly you should update the source document first and then
      replace the embedded document so the \`_rev\` property matches.

`;


var usage = function() {
  console.error(usageInfo);
  process.exit(1);
};

if (process.argv.indexOf('-a') !== -1) {
  options.updateAll = true;
  process.argv.splice(process.argv.indexOf('-a'), 1);
}

if (process.argv.indexOf('-h') !== -1) {
  usage();
}

if (process.argv.length < 3) {
  console.error('\nError: Please provide the file system path to the index.');
  usage();
} else {
  tmp = require(path.resolve(process.argv[2]));
  tmp.forEach(function(obj) {
    var id = obj.id;
    delete(obj.id);
    index[id] = obj;
  });
}

// null is not an object
var isObject = function (obj) {
  return Boolean(obj && typeof obj === 'object');
};

/*
 * If the property is an object and not null continue walking, if we see an _id
 * property check the index for a match and try to update its properties.
 */
var walkProperties = function(data) {
  Object.keys(data).forEach(function(k) {
    if (k === '_id' && index[data[k]]) {
      if (updates[data[k]] && !options.updateAll) {
        // only modify embedded docs when update all flag is set.
        return;
      }
      data = _.extend(data, index[data[k]]);
      updates[data[k]] = true;
      stats.updates++;
    } else if (data[k] && typeof data[k] === 'object') {
      walkProperties(data[k]);
    }
  });
};

process.stdin.setEncoding('utf8');

process.stdin.on('data', function (chunk) {
  input += chunk;
});

process.stdin.on('end', function () {
  var data = JSON.parse(input);
  if (data.docs) {
    data = data.docs;
  } else if (data.rows) {
    data = data.rows;
  } else if (!Array.isArray(data)) {
    data = [data];
  }
  data.forEach(function(doc) {
    // skip null values
    if (!isObject(doc)) {
      return;
    }
    stats.docs++;
    walkProperties(doc.doc || doc);
  });
  process.stdout.write(JSON.stringify({docs: data}));
  console.error(stats);
});
