#!/usr/bin/env node

var flat = require('flat'),
    input = '';

process.stdin.setEncoding('utf8');

process.stdin.on('data', function (chunk) {
  input += chunk;
});

process.stdin.on('end', function () {
  var data = JSON.parse(input);
  process.stdout.write(JSON.stringify(flat.flatten(data)));
});

