#!/usr/bin/env node
var path = require('path');

var input = '',
    stats = { docs: 0, updates: 0 },
    docPath,
    doc;

if (process.argv.length !== 3) {
  console.error('Please provide the file system path to a doc.');
  process.exit(1);
} else {
  docPath = process.argv[2];
  doc = require(path.resolve(docPath));
}

var isObject = function (obj) {
  return Boolean(obj && typeof obj === 'object');
};

var updateEmbedded = function(data) {
  Object.keys(data).forEach(function(k) {
    if (data[k] && typeof data[k] === 'object') {
      if (data[k]._id === doc._id) {
        data[k] = doc;
        stats.updates++;
      } else {
        updateEmbedded(data[k]);
      }
    }
  });
};

process.stdin.setEncoding('utf8');

process.stdin.on('data', function (chunk) {
  input += chunk;
});

process.stdin.on('end', function () {
  var data = JSON.parse(input);
  if (data.docs) {
    data = data.docs;
  } else if (data.rows) {
    data = data.rows;
  } else if (!Array.isArray(data)) {
    data = [data];
  }
  data.forEach(function(doc) {
    // skip null values
    if (!isObject(doc)) {
      return;
    }
    stats.docs++;
    updateEmbedded(doc.doc || doc);
  });
  process.stdout.write(JSON.stringify({docs: data}));
  console.error(stats);
});
