#!/usr/bin/env node
/*
 * npm install fast-csv 
 */

var fs = require('fs'),
    path = require('path'),
    csv = require('fast-csv');

var self = process.argv[1].split(path.sep).pop();

var usage = function() {
  console.log("");
  console.log("Usage: cat csv_file(s) | ./%s", self);
  console.log("");
  console.log("Description:");
  console.log("");
  console.log("  Filter CSV data, finds then prints CSV formatted data.");
  console.log("");
  process.exit(1);
};

var output = { keys: [] };
var handleRow = function(obj) {
  output.keys.push('org.couchdb.user:' + obj.username);
};

var finish = function() {
  console.error('done parsing rows');
  console.log(JSON.stringify(output));
};

csv
 //.fromPath(file, {headers: true})
 .fromStream(process.stdin, {headers: true})
 //.transform(transform)
 .on("data", handleRow)
 .on("end", finish)
 //.pipe(csv.createWriteStream({headers: true}))
 //.pipe(process.stdout)
